/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package betav1

import (
	time "time"

	queueentryoperator_betav1 "github.com/podnov/k8s-queue-entry-operator/pkg/apis/queueentryoperator/betav1"
	clientset "github.com/podnov/k8s-queue-entry-operator/pkg/client/clientset/internalclientset"
	internalinterfaces "github.com/podnov/k8s-queue-entry-operator/pkg/client/informers/informers_generated/externalversions/internalinterfaces"
	betav1 "github.com/podnov/k8s-queue-entry-operator/pkg/client/listers/queueentryoperator/betav1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DbQueueInformer provides access to a shared informer and lister for
// DbQueues.
type DbQueueInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() betav1.DbQueueLister
}

type dbQueueInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewDbQueueInformer constructs a new informer for DbQueue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDbQueueInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.QueueentryoperatorBetav1().DbQueues(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.QueueentryoperatorBetav1().DbQueues(namespace).Watch(options)
			},
		},
		&queueentryoperator_betav1.DbQueue{},
		resyncPeriod,
		indexers,
	)
}

func defaultDbQueueInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewDbQueueInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *dbQueueInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&queueentryoperator_betav1.DbQueue{}, defaultDbQueueInformer)
}

func (f *dbQueueInformer) Lister() betav1.DbQueueLister {
	return betav1.NewDbQueueLister(f.Informer().GetIndexer())
}
