/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package betav1

import (
	betav1 "github.com/podnov/k8s-queue-entry-operator/pkg/apis/queueentryoperator/betav1"
	scheme "github.com/podnov/k8s-queue-entry-operator/pkg/client/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DbQueuesGetter has a method to return a DbQueueInterface.
// A group's client should implement this interface.
type DbQueuesGetter interface {
	DbQueues(namespace string) DbQueueInterface
}

// DbQueueInterface has methods to work with DbQueue resources.
type DbQueueInterface interface {
	Create(*betav1.DbQueue) (*betav1.DbQueue, error)
	Update(*betav1.DbQueue) (*betav1.DbQueue, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*betav1.DbQueue, error)
	List(opts v1.ListOptions) (*betav1.DbQueueList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *betav1.DbQueue, err error)
	DbQueueExpansion
}

// dbQueues implements DbQueueInterface
type dbQueues struct {
	client rest.Interface
	ns     string
}

// newDbQueues returns a DbQueues
func newDbQueues(c *QueueentryoperatorBetav1Client, namespace string) *dbQueues {
	return &dbQueues{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dbQueue, and returns the corresponding dbQueue object, and an error if there is any.
func (c *dbQueues) Get(name string, options v1.GetOptions) (result *betav1.DbQueue, err error) {
	result = &betav1.DbQueue{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dbqueues").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DbQueues that match those selectors.
func (c *dbQueues) List(opts v1.ListOptions) (result *betav1.DbQueueList, err error) {
	result = &betav1.DbQueueList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dbqueues").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dbQueues.
func (c *dbQueues) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dbqueues").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a dbQueue and creates it.  Returns the server's representation of the dbQueue, and an error, if there is any.
func (c *dbQueues) Create(dbQueue *betav1.DbQueue) (result *betav1.DbQueue, err error) {
	result = &betav1.DbQueue{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dbqueues").
		Body(dbQueue).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dbQueue and updates it. Returns the server's representation of the dbQueue, and an error, if there is any.
func (c *dbQueues) Update(dbQueue *betav1.DbQueue) (result *betav1.DbQueue, err error) {
	result = &betav1.DbQueue{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dbqueues").
		Name(dbQueue.Name).
		Body(dbQueue).
		Do().
		Into(result)
	return
}

// Delete takes name of the dbQueue and deletes it. Returns an error if one occurs.
func (c *dbQueues) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dbqueues").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dbQueues) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dbqueues").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dbQueue.
func (c *dbQueues) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *betav1.DbQueue, err error) {
	result = &betav1.DbQueue{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dbqueues").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
