/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	betav1 "github.com/podnov/k8s-queue-entry-operator/pkg/apis/queueentryoperator/betav1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDbQueues implements DbQueueInterface
type FakeDbQueues struct {
	Fake *FakeQueueentryoperatorBetav1
	ns   string
}

var dbqueuesResource = schema.GroupVersionResource{Group: "queueentryoperator", Version: "betav1", Resource: "dbqueues"}

var dbqueuesKind = schema.GroupVersionKind{Group: "queueentryoperator", Version: "betav1", Kind: "DbQueue"}

// Get takes name of the dbQueue, and returns the corresponding dbQueue object, and an error if there is any.
func (c *FakeDbQueues) Get(name string, options v1.GetOptions) (result *betav1.DbQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dbqueuesResource, c.ns, name), &betav1.DbQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*betav1.DbQueue), err
}

// List takes label and field selectors, and returns the list of DbQueues that match those selectors.
func (c *FakeDbQueues) List(opts v1.ListOptions) (result *betav1.DbQueueList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dbqueuesResource, dbqueuesKind, c.ns, opts), &betav1.DbQueueList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &betav1.DbQueueList{}
	for _, item := range obj.(*betav1.DbQueueList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dbQueues.
func (c *FakeDbQueues) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dbqueuesResource, c.ns, opts))

}

// Create takes the representation of a dbQueue and creates it.  Returns the server's representation of the dbQueue, and an error, if there is any.
func (c *FakeDbQueues) Create(dbQueue *betav1.DbQueue) (result *betav1.DbQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dbqueuesResource, c.ns, dbQueue), &betav1.DbQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*betav1.DbQueue), err
}

// Update takes the representation of a dbQueue and updates it. Returns the server's representation of the dbQueue, and an error, if there is any.
func (c *FakeDbQueues) Update(dbQueue *betav1.DbQueue) (result *betav1.DbQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dbqueuesResource, c.ns, dbQueue), &betav1.DbQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*betav1.DbQueue), err
}

// Delete takes name of the dbQueue and deletes it. Returns an error if one occurs.
func (c *FakeDbQueues) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dbqueuesResource, c.ns, name), &betav1.DbQueue{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDbQueues) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dbqueuesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &betav1.DbQueueList{})
	return err
}

// Patch applies the patch and returns the patched dbQueue.
func (c *FakeDbQueues) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *betav1.DbQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dbqueuesResource, c.ns, name, data, subresources...), &betav1.DbQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*betav1.DbQueue), err
}
